kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ (.Values.postgres.password) | b64enc }}
  POSTGRES_USER: {{ (.Values.postgres.user) | b64enc }}